/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontSize: {
        // Sistema di font unificato per la piattaforma
        caption: ["0.75rem", { lineHeight: "1rem" }], // 12px - Per caption e note
        "body-sm": ["0.875rem", { lineHeight: "1.25rem" }], // 14px - Per testo piccolo
        body: ["1rem", { lineHeight: "1.5rem" }], // 16px - Testo principale
        "body-lg": ["1.125rem", { lineHeight: "1.75rem" }], // 18px - Testo enfatizzato
        "heading-sm": ["1.25rem", { lineHeight: "1.75rem" }], // 20px - Sottotitoli
        heading: ["1.5rem", { lineHeight: "2rem" }], // 24px - Titoli sezioni
        "heading-lg": ["1.875rem", { lineHeight: "2.25rem" }], // 30px - Titoli principali
        display: ["2.25rem", { lineHeight: "2.5rem" }], // 36px - Titoli pagina
        "display-lg": ["3rem", { lineHeight: "1" }], // 48px - Titoli hero
      },
      animation: {
        "spin-slow": "spin 3s linear infinite",
        "scroll-down": "scrollDown 30s linear infinite",
        "scroll-down-slow": "scrollDown 40s linear infinite",
        "scroll-down-fast": "scrollDown 25s linear infinite",
      },
      keyframes: {
        scrollDown: {
          "0%": { transform: "translateY(0)" },
          "100%": { transform: "translateY(-50%)" },
        },
      },
      colors: {
        "agri-green": {
          50: "rgb(var(--palette-agri-green-50) / <alpha-value>)",
          100: "rgb(var(--palette-agri-green-100) / <alpha-value>)",
          200: "rgb(var(--palette-agri-green-200) / <alpha-value>)",
          300: "rgb(var(--palette-agri-green-300) / <alpha-value>)",
          400: "rgb(var(--palette-agri-green-400) / <alpha-value>)",
          500: "rgb(var(--palette-agri-green-500) / <alpha-value>)",
          600: "rgb(var(--palette-agri-green-600) / <alpha-value>)",
          700: "rgb(var(--palette-agri-green-700) / <alpha-value>)",
          800: "rgb(var(--palette-agri-green-800) / <alpha-value>)",
          900: "rgb(var(--palette-agri-green-900) / <alpha-value>)",
          950: "rgb(var(--palette-agri-green-950) / <alpha-value>)",
        },
        harvest: {
          100: "#fdf6e3", // Sfondo crema chiaro
          200: "#f8edca", // Paglia chiara
          300: "#eed592", // Paglia
          400: "#d9b362", // Paglia scura
          500: "#a0955a", // Grano
          600: "#5a5530", // Terra
        },
        field: {
          100: "#e9f5fd", // Cielo chiaro
          200: "#c5e3fa", // Cielo
          300: "#86b9dd", // Cielo più scuro
          400: "#5b8ba6", // Blu sfumato dell'orizzonte
          500: "#3a566b", // Blu profondo
          600: "#18293d", // Blu notte
        },
        nature: {
          100: "#f1f8e9", // Verde chiaro
          200: "#dcedc8", // Verde medio chiaro
          300: "#6a8d54", // Verde campo
          400: "#4c7031", // Verde scuro
          500: "#344a1f", // Verde molto scuro
          600: "#20341a", // Verde quasi nero
        },
        white: "rgb(var(--palette-white) / <alpha-value>)",
        black: "rgb(var(--palette-black) / <alpha-value>)",
        green: {
          50: "rgb(var(--palette-green-50) / <alpha-value>)",
          100: "rgb(var(--palette-green-100) / <alpha-value>)",
          200: "rgb(var(--palette-green-200) / <alpha-value>)",
          300: "rgb(var(--palette-green-300) / <alpha-value>)",
          400: "rgb(var(--palette-green-400) / <alpha-value>)",
          500: "rgb(var(--palette-green-500) / <alpha-value>)",
          600: "rgb(var(--palette-green-600) / <alpha-value>)",
          700: "rgb(var(--palette-green-700) / <alpha-value>)",
          800: "rgb(var(--palette-green-800) / <alpha-value>)",
          900: "rgb(var(--palette-green-900) / <alpha-value>)",
          950: "rgb(var(--palette-green-950) / <alpha-value>)",
        },
        amber: {
          50: "rgb(var(--palette-amber-50) / <alpha-value>)",
          100: "rgb(var(--palette-amber-100) / <alpha-value>)",
          200: "rgb(var(--palette-amber-200) / <alpha-value>)",
          300: "rgb(var(--palette-amber-300) / <alpha-value>)",
          400: "rgb(var(--palette-amber-400) / <alpha-value>)",
          500: "rgb(var(--palette-amber-500) / <alpha-value>)",
          600: "rgb(var(--palette-amber-600) / <alpha-value>)",
          700: "rgb(var(--palette-amber-700) / <alpha-value>)",
          800: "rgb(var(--palette-amber-800) / <alpha-value>)",
          900: "rgb(var(--palette-amber-900) / <alpha-value>)",
          950: "rgb(var(--palette-amber-950) / <alpha-value>)",
        },
        red: {
          50: "rgb(var(--palette-red-50) / <alpha-value>)",
          100: "rgb(var(--palette-red-100) / <alpha-value>)",
          200: "rgb(var(--palette-red-200) / <alpha-value>)",
          300: "rgb(var(--palette-red-300) / <alpha-value>)",
          400: "rgb(var(--palette-red-400) / <alpha-value>)",
          500: "rgb(var(--palette-red-500) / <alpha-value>)",
          600: "rgb(var(--palette-red-600) / <alpha-value>)",
          700: "rgb(var(--palette-red-700) / <alpha-value>)",
          800: "rgb(var(--palette-red-800) / <alpha-value>)",
          900: "rgb(var(--palette-red-900) / <alpha-value>)",
          950: "rgb(var(--palette-red-950) / <alpha-value>)",
        },
        yellow: {
          50: "rgb(var(--palette-yellow-50) / <alpha-value>)",
          100: "rgb(var(--palette-yellow-100) / <alpha-value>)",
          200: "rgb(var(--palette-yellow-200) / <alpha-value>)",
          300: "rgb(var(--palette-yellow-300) / <alpha-value>)",
          400: "rgb(var(--palette-yellow-400) / <alpha-value>)",
          500: "rgb(var(--palette-yellow-500) / <alpha-value>)",
          600: "rgb(var(--palette-yellow-600) / <alpha-value>)",
          700: "rgb(var(--palette-yellow-700) / <alpha-value>)",
          800: "rgb(var(--palette-yellow-800) / <alpha-value>)",
          900: "rgb(var(--palette-yellow-900) / <alpha-value>)",
          950: "rgb(var(--palette-yellow-950) / <alpha-value>)",
        },
        orange: {
          50: "rgb(var(--palette-orange-50) / <alpha-value>)",
          100: "rgb(var(--palette-orange-100) / <alpha-value>)",
          200: "rgb(var(--palette-orange-200) / <alpha-value>)",
          300: "rgb(var(--palette-orange-300) / <alpha-value>)",
          400: "rgb(var(--palette-orange-400) / <alpha-value>)",
          500: "rgb(var(--palette-orange-500) / <alpha-value>)",
          600: "rgb(var(--palette-orange-600) / <alpha-value>)",
          700: "rgb(var(--palette-orange-700) / <alpha-value>)",
          800: "rgb(var(--palette-orange-800) / <alpha-value>)",
          900: "rgb(var(--palette-orange-900) / <alpha-value>)",
          950: "rgb(var(--palette-orange-950) / <alpha-value>)",
        },
        rose: {
          50: "rgb(var(--palette-rose-50) / <alpha-value>)",
          100: "rgb(var(--palette-rose-100) / <alpha-value>)",
          200: "rgb(var(--palette-rose-200) / <alpha-value>)",
          300: "rgb(var(--palette-rose-300) / <alpha-value>)",
          400: "rgb(var(--palette-rose-400) / <alpha-value>)",
          500: "rgb(var(--palette-rose-500) / <alpha-value>)",
          600: "rgb(var(--palette-rose-600) / <alpha-value>)",
          700: "rgb(var(--palette-rose-700) / <alpha-value>)",
          800: "rgb(var(--palette-rose-800) / <alpha-value>)",
          900: "rgb(var(--palette-rose-900) / <alpha-value>)",
          950: "rgb(var(--palette-rose-950) / <alpha-value>)",
        },
        blue: {
          50: "rgb(var(--palette-blue-50) / <alpha-value>)",
          100: "rgb(var(--palette-blue-100) / <alpha-value>)",
          200: "rgb(var(--palette-blue-200) / <alpha-value>)",
          300: "rgb(var(--palette-blue-300) / <alpha-value>)",
          400: "rgb(var(--palette-blue-400) / <alpha-value>)",
          500: "rgb(var(--palette-blue-500) / <alpha-value>)",
          600: "rgb(var(--palette-blue-600) / <alpha-value>)",
          700: "rgb(var(--palette-blue-700) / <alpha-value>)",
          800: "rgb(var(--palette-blue-800) / <alpha-value>)",
          900: "rgb(var(--palette-blue-900) / <alpha-value>)",
          950: "rgb(var(--palette-blue-950) / <alpha-value>)",
        },
        indigo: {
          50: "rgb(var(--palette-indigo-50) / <alpha-value>)",
          100: "rgb(var(--palette-indigo-100) / <alpha-value>)",
          200: "rgb(var(--palette-indigo-200) / <alpha-value>)",
          300: "rgb(var(--palette-indigo-300) / <alpha-value>)",
          400: "rgb(var(--palette-indigo-400) / <alpha-value>)",
          500: "rgb(var(--palette-indigo-500) / <alpha-value>)",
          600: "rgb(var(--palette-indigo-600) / <alpha-value>)",
          700: "rgb(var(--palette-indigo-700) / <alpha-value>)",
          800: "rgb(var(--palette-indigo-800) / <alpha-value>)",
          900: "rgb(var(--palette-indigo-900) / <alpha-value>)",
          950: "rgb(var(--palette-indigo-950) / <alpha-value>)",
        },
        purple: {
          50: "rgb(var(--palette-purple-50) / <alpha-value>)",
          100: "rgb(var(--palette-purple-100) / <alpha-value>)",
          200: "rgb(var(--palette-purple-200) / <alpha-value>)",
          300: "rgb(var(--palette-purple-300) / <alpha-value>)",
          400: "rgb(var(--palette-purple-400) / <alpha-value>)",
          500: "rgb(var(--palette-purple-500) / <alpha-value>)",
          600: "rgb(var(--palette-purple-600) / <alpha-value>)",
          700: "rgb(var(--palette-purple-700) / <alpha-value>)",
          800: "rgb(var(--palette-purple-800) / <alpha-value>)",
          900: "rgb(var(--palette-purple-900) / <alpha-value>)",
          950: "rgb(var(--palette-purple-950) / <alpha-value>)",
        },
        violet: {
          50: "rgb(var(--palette-violet-50) / <alpha-value>)",
          100: "rgb(var(--palette-violet-100) / <alpha-value>)",
          200: "rgb(var(--palette-violet-200) / <alpha-value>)",
          300: "rgb(var(--palette-violet-300) / <alpha-value>)",
          400: "rgb(var(--palette-violet-400) / <alpha-value>)",
          500: "rgb(var(--palette-violet-500) / <alpha-value>)",
          600: "rgb(var(--palette-violet-600) / <alpha-value>)",
          700: "rgb(var(--palette-violet-700) / <alpha-value>)",
          800: "rgb(var(--palette-violet-800) / <alpha-value>)",
          900: "rgb(var(--palette-violet-900) / <alpha-value>)",
          950: "rgb(var(--palette-violet-950) / <alpha-value>)",
        },
        fuchsia: {
          50: "rgb(var(--palette-fuchsia-50) / <alpha-value>)",
          100: "rgb(var(--palette-fuchsia-100) / <alpha-value>)",
          200: "rgb(var(--palette-fuchsia-200) / <alpha-value>)",
          300: "rgb(var(--palette-fuchsia-300) / <alpha-value>)",
          400: "rgb(var(--palette-fuchsia-400) / <alpha-value>)",
          500: "rgb(var(--palette-fuchsia-500) / <alpha-value>)",
          600: "rgb(var(--palette-fuchsia-600) / <alpha-value>)",
          700: "rgb(var(--palette-fuchsia-700) / <alpha-value>)",
          800: "rgb(var(--palette-fuchsia-800) / <alpha-value>)",
          900: "rgb(var(--palette-fuchsia-900) / <alpha-value>)",
          950: "rgb(var(--palette-fuchsia-950) / <alpha-value>)",
        },
        pink: {
          50: "rgb(var(--palette-pink-50) / <alpha-value>)",
          100: "rgb(var(--palette-pink-100) / <alpha-value>)",
          200: "rgb(var(--palette-pink-200) / <alpha-value>)",
          300: "rgb(var(--palette-pink-300) / <alpha-value>)",
          400: "rgb(var(--palette-pink-400) / <alpha-value>)",
          500: "rgb(var(--palette-pink-500) / <alpha-value>)",
          600: "rgb(var(--palette-pink-600) / <alpha-value>)",
          700: "rgb(var(--palette-pink-700) / <alpha-value>)",
          800: "rgb(var(--palette-pink-800) / <alpha-value>)",
          900: "rgb(var(--palette-pink-900) / <alpha-value>)",
          950: "rgb(var(--palette-pink-950) / <alpha-value>)",
        },
        teal: {
          50: "rgb(var(--palette-teal-50) / <alpha-value>)",
          100: "rgb(var(--palette-teal-100) / <alpha-value>)",
          200: "rgb(var(--palette-teal-200) / <alpha-value>)",
          300: "rgb(var(--palette-teal-300) / <alpha-value>)",
          400: "rgb(var(--palette-teal-400) / <alpha-value>)",
          500: "rgb(var(--palette-teal-500) / <alpha-value>)",
          600: "rgb(var(--palette-teal-600) / <alpha-value>)",
          700: "rgb(var(--palette-teal-700) / <alpha-value>)",
          800: "rgb(var(--palette-teal-800) / <alpha-value>)",
          900: "rgb(var(--palette-teal-900) / <alpha-value>)",
          950: "rgb(var(--palette-teal-950) / <alpha-value>)",
        },
        emerald: {
          50: "rgb(var(--palette-emerald-50) / <alpha-value>)",
          100: "rgb(var(--palette-emerald-100) / <alpha-value>)",
          200: "rgb(var(--palette-emerald-200) / <alpha-value>)",
          300: "rgb(var(--palette-emerald-300) / <alpha-value>)",
          400: "rgb(var(--palette-emerald-400) / <alpha-value>)",
          500: "rgb(var(--palette-emerald-500) / <alpha-value>)",
          600: "rgb(var(--palette-emerald-600) / <alpha-value>)",
          700: "rgb(var(--palette-emerald-700) / <alpha-value>)",
          800: "rgb(var(--palette-emerald-800) / <alpha-value>)",
          900: "rgb(var(--palette-emerald-900) / <alpha-value>)",
          950: "rgb(var(--palette-emerald-950) / <alpha-value>)",
        },
        lime: {
          50: "rgb(var(--palette-lime-50) / <alpha-value>)",
          100: "rgb(var(--palette-lime-100) / <alpha-value>)",
          200: "rgb(var(--palette-lime-200) / <alpha-value>)",
          300: "rgb(var(--palette-lime-300) / <alpha-value>)",
          400: "rgb(var(--palette-lime-400) / <alpha-value>)",
          500: "rgb(var(--palette-lime-500) / <alpha-value>)",
          600: "rgb(var(--palette-lime-600) / <alpha-value>)",
          700: "rgb(var(--palette-lime-700) / <alpha-value>)",
          800: "rgb(var(--palette-lime-800) / <alpha-value>)",
          900: "rgb(var(--palette-lime-900) / <alpha-value>)",
          950: "rgb(var(--palette-lime-950) / <alpha-value>)",
        },
        cyan: {
          50: "rgb(var(--palette-cyan-50) / <alpha-value>)",
          100: "rgb(var(--palette-cyan-100) / <alpha-value>)",
          200: "rgb(var(--palette-cyan-200) / <alpha-value>)",
          300: "rgb(var(--palette-cyan-300) / <alpha-value>)",
          400: "rgb(var(--palette-cyan-400) / <alpha-value>)",
          500: "rgb(var(--palette-cyan-500) / <alpha-value>)",
          600: "rgb(var(--palette-cyan-600) / <alpha-value>)",
          700: "rgb(var(--palette-cyan-700) / <alpha-value>)",
          800: "rgb(var(--palette-cyan-800) / <alpha-value>)",
          900: "rgb(var(--palette-cyan-900) / <alpha-value>)",
          950: "rgb(var(--palette-cyan-950) / <alpha-value>)",
        },
        sky: {
          50: "rgb(var(--palette-sky-50) / <alpha-value>)",
          100: "rgb(var(--palette-sky-100) / <alpha-value>)",
          200: "rgb(var(--palette-sky-200) / <alpha-value>)",
          300: "rgb(var(--palette-sky-300) / <alpha-value>)",
          400: "rgb(var(--palette-sky-400) / <alpha-value>)",
          500: "rgb(var(--palette-sky-500) / <alpha-value>)",
          600: "rgb(var(--palette-sky-600) / <alpha-value>)",
          700: "rgb(var(--palette-sky-700) / <alpha-value>)",
          800: "rgb(var(--palette-sky-800) / <alpha-value>)",
          900: "rgb(var(--palette-sky-900) / <alpha-value>)",
          950: "rgb(var(--palette-sky-950) / <alpha-value>)",
        },
        slate: {
          50: "rgb(var(--palette-slate-50) / <alpha-value>)",
          100: "rgb(var(--palette-slate-100) / <alpha-value>)",
          200: "rgb(var(--palette-slate-200) / <alpha-value>)",
          300: "rgb(var(--palette-slate-300) / <alpha-value>)",
          400: "rgb(var(--palette-slate-400) / <alpha-value>)",
          500: "rgb(var(--palette-slate-500) / <alpha-value>)",
          600: "rgb(var(--palette-slate-600) / <alpha-value>)",
          700: "rgb(var(--palette-slate-700) / <alpha-value>)",
          800: "rgb(var(--palette-slate-800) / <alpha-value>)",
          900: "rgb(var(--palette-slate-900) / <alpha-value>)",
          950: "rgb(var(--palette-slate-950) / <alpha-value>)",
        },
        zinc: {
          50: "rgb(var(--palette-zinc-50) / <alpha-value>)",
          100: "rgb(var(--palette-zinc-100) / <alpha-value>)",
          200: "rgb(var(--palette-zinc-200) / <alpha-value>)",
          300: "rgb(var(--palette-zinc-300) / <alpha-value>)",
          400: "rgb(var(--palette-zinc-400) / <alpha-value>)",
          500: "rgb(var(--palette-zinc-500) / <alpha-value>)",
          600: "rgb(var(--palette-zinc-600) / <alpha-value>)",
          700: "rgb(var(--palette-zinc-700) / <alpha-value>)",
          800: "rgb(var(--palette-zinc-800) / <alpha-value>)",
          900: "rgb(var(--palette-zinc-900) / <alpha-value>)",
          950: "rgb(var(--palette-zinc-950) / <alpha-value>)",
        },
        stone: {
          50: "rgb(var(--palette-stone-50) / <alpha-value>)",
          100: "rgb(var(--palette-stone-100) / <alpha-value>)",
          200: "rgb(var(--palette-stone-200) / <alpha-value>)",
          300: "rgb(var(--palette-stone-300) / <alpha-value>)",
          400: "rgb(var(--palette-stone-400) / <alpha-value>)",
          500: "rgb(var(--palette-stone-500) / <alpha-value>)",
          600: "rgb(var(--palette-stone-600) / <alpha-value>)",
          700: "rgb(var(--palette-stone-700) / <alpha-value>)",
          800: "rgb(var(--palette-stone-800) / <alpha-value>)",
          900: "rgb(var(--palette-stone-900) / <alpha-value>)",
          950: "rgb(var(--palette-stone-950) / <alpha-value>)",
        },
        gray: {
          50: "rgb(var(--palette-gray-50) / <alpha-value>)",
          100: "rgb(var(--palette-gray-100) / <alpha-value>)",
          200: "rgb(var(--palette-gray-200) / <alpha-value>)",
          300: "rgb(var(--palette-gray-300) / <alpha-value>)",
          400: "rgb(var(--palette-gray-400) / <alpha-value>)",
          500: "rgb(var(--palette-gray-500) / <alpha-value>)",
          600: "rgb(var(--palette-gray-600) / <alpha-value>)",
          700: "rgb(var(--palette-gray-700) / <alpha-value>)",
          800: "rgb(var(--palette-gray-800) / <alpha-value>)",
          900: "rgb(var(--palette-gray-900) / <alpha-value>)",
          950: "rgb(var(--palette-gray-950) / <alpha-value>)",
        },
        neutral: {
          50: "rgb(var(--palette-neutral-50) / <alpha-value>)",
          100: "rgb(var(--palette-neutral-100) / <alpha-value>)",
          200: "rgb(var(--palette-neutral-200) / <alpha-value>)",
          300: "rgb(var(--palette-neutral-300) / <alpha-value>)",
          400: "rgb(var(--palette-neutral-400) / <alpha-value>)",
          500: "rgb(var(--palette-neutral-500) / <alpha-value>)",
          600: "rgb(var(--palette-neutral-600) / <alpha-value>)",
          700: "rgb(var(--palette-neutral-700) / <alpha-value>)",
          800: "rgb(var(--palette-neutral-800) / <alpha-value>)",
          900: "rgb(var(--palette-neutral-900) / <alpha-value>)",
          950: "rgb(var(--palette-neutral-950) / <alpha-value>)",
        },
      },
    },
  },
  plugins: [],
};
