export const feedbacks = [
  {
    id: 1,
    name: "Marco Rossi",
    initials: "MR",
    role: "Agricoltore, Toscana",
    text: "Come azienda agricola, dobbiamo gestire tanti campi diversi. Seminai ha reso tutto più semplice. La nostra produttività è aumentata del 40%. Strumento essenziale per ogni agricoltore moderno.",
    highlight: "La nostra produttività è aumentata del 40%.",
    color: "blue",
  },
  {
    id: 2,
    name: "Lucia Bianchi",
    initials: "LB",
    role: "Direttrice cooperativa agricola",
    text: "L'implementazione di Seminai nei nostri processi ha migliorato notevolmente la gestione dei campi. Tecnologia e agricoltura che lavorano insieme per risultati migliori. Una svolta per l'agricoltura di precisione.",
    highlight:
      "Tecnologia e agricoltura che lavorano insieme per risultati migliori.",
    color: "blue",
  },
  {
    id: 3,
    name: "Sofia Neri",
    initials: "SN",
    role: "Agronoma consulente",
    text: "Consiglio vivamente Seminai ai miei clienti. Il team è professionale e reattivo. Ha trasformato completamente la gestione delle operazioni agricole.",
    highlight:
      "Ha trasformato completamente la gestione delle operazioni agricole.",
    color: "rose",
  },
  {
    id: 4,
    name: "Giovanni Marino",
    initials: "GM",
    role: "Titolare azienda biologica",
    text: "Integrando Seminai nella nostra azienda biologica, abbiamo visto una significativa riduzione degli sprechi di risorse. All'avanguardia nelle pratiche agricole eco-sostenibili. Un pioniere del cambiamento nel settore.",
    highlight: "All'avanguardia nelle pratiche agricole eco-sostenibili.",
    color: "green",
  },
  {
    id: 5,
    name: "Andrea Ferrari",
    initials: "AF",
    role: "CTO Agricoltura Innovativa",
    text: "L'analisi guidata dall'IA di Seminai ha rivoluzionato il nostro ciclo di sviluppo produttivo. I dati sono ora più accurati e disponibili in tempo reale. Un punto di svolta per le aziende agricole tecnologiche.",
    highlight: "I dati sono ora più accurati e disponibili in tempo reale.",
    color: "purple",
  },
  {
    id: 6,
    name: "Roberto Verdi",
    initials: "RV",
    role: "Responsabile viticoltura",
    text: "Seminai ha trasformato il modo in cui gestiamo i nostri vigneti. Le nostre operazioni sono ora basate su dati precisi con maggiore produttività e qualità. Rivoluzionando la viticoltura moderna.",
    highlight:
      "Le nostre operazioni sono ora basate su dati precisi con maggiore produttività e qualità.",
    color: "orange",
  },
  {
    id: 7,
    name: "Elena Sorrentino",
    initials: "ES",
    role: "Responsabile filiera agricola",
    text: "Seminai ha semplificato il nostro processo creativo, migliorando produttività e innovazione nella filiera. Unisce creatività e tecnologia in agricoltura. Un game-changer per il settore agricolo moderno.",
    highlight: "Unisce creatività e tecnologia in agricoltura.",
    color: "pink",
  },
  {
    id: 8,
    name: "Paolo Conti",
    initials: "PC",
    role: "Direttore tecnico, AgroSicurezza",
    text: "Con i sistemi di sicurezza di Seminai, i nostri dati agricoli sono protetti a livelli imbattibili. Garantisce sicurezza e affidabilità nel mondo digitale agricolo. Ridefinisce gli standard di sicurezza per l'agritech.",
    highlight:
      "Garantisce sicurezza e affidabilità nel mondo digitale agricolo.",
    color: "cyan",
  },
  {
    id: 9,
    name: "Matteo Tosi",
    initials: "MT",
    role: "Direttore formazione agricola",
    text: "I piani personalizzati di Seminai hanno raddoppiato le prestazioni dei nostri studenti in agraria. Formazione agricola su misura per ogni studente. Trasforma il panorama educativo agricolo italiano.",
    highlight: "Formazione agricola su misura per ogni studente.",
    color: "indigo",
  },
];
